// <auto-generated />
namespace CottonDBMS.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSplitWeightColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSplitWeightColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201906252135596_AddSplitWeightColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
